export const  mockEmptyCollections = []
export const  mockCollections = [
	{
		"id":3,
		"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/collections\/3",
		"public":true,
		"featured":true,
		"added":"2016-08-15T14:50:20+00:00",
		"modified":"2019-07-09T15:05:29+00:00",
		"owner":{
			"id":1,
			"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/users\/1",
			"resource":"users"
		},
		"items":{
			"count":0,
			"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/items?collection=3",
			"resource":"items"
		},
		"element_texts":[
			{
				"html":false,
				"text":"Tools",
				"element_set":{
					"id":1,
					"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/element_sets\/1",
					"name":"Dublin Core",
					"resource":"element_sets"
				},
				"element":{
					"id":50,
					"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/elements\/50",
					"name":"Title",
					"resource":"elements"
				}
			}
		],
		"extended_resources":[

		]
	},
	{
		"id":6,
		"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/collections\/6",
		"public":true,
		"featured":true,
		"added":"2016-08-15T14:50:58+00:00",
		"modified":"2019-07-09T15:05:24+00:00",
		"owner":{
			"id":1,
			"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/users\/1",
			"resource":"users"
		},
		"items":{
			"count":1,
			"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/items?collection=6",
			"resource":"items"
		},
		"element_texts":[
			{
				"html":false,
				"text":"Paper Creations",
				"element_set":{
					"id":1,
					"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/element_sets\/1",
					"name":"Dublin Core",
					"resource":"element_sets"
				},
				"element":{
					"id":50,
					"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/elements\/50",
					"name":"Title",
					"resource":"elements"
				}
			}
		],
		"extended_resources":[

		]
	},
	{
		"id":7,
		"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/collections\/7",
		"public":true,
		"featured":true,
		"added":"2016-08-15T14:51:09+00:00",
		"modified":"2019-07-09T15:05:41+00:00",
		"owner":{
			"id":1,
			"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/users\/1",
			"resource":"users"
		},
		"items":{
			"count":2,
			"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/items?collection=7",
			"resource":"items"
		},
		"element_texts":[
			{
				"html":false,
				"text":"Artisans",
				"element_set":{
					"id":1,
					"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/element_sets\/1",
					"name":"Dublin Core",
					"resource":"element_sets"
				},
				"element":{
					"id":50,
					"url":"http:\/\/s-lib018.lib.uiowa.edu\/soteriou_omeka\/api\/elements\/50",
					"name":"Title",
					"resource":"elements"
				}
			}
		],
		"extended_resources":[

		]
	}]